//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.31 at 05:57:36 AM PST 
//


package com.wagstaffnet.tivo.app.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TvBusEnvelopeVActualShowingElementProgramVActorElement_QNAME = new QName("", "element");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TvBusEnvelope }
     * 
     */
    public TvBusEnvelope createTvBusEnvelope() {
        return new TvBusEnvelope();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.BitstreamFormat }
     * 
     */
    public TvBusEnvelope.BitstreamFormat createTvBusEnvelopeBitstreamFormat() {
        return new TvBusEnvelope.BitstreamFormat();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.BitstreamFormat.VFormat }
     * 
     */
    public TvBusEnvelope.BitstreamFormat.VFormat createTvBusEnvelopeBitstreamFormatVFormat() {
        return new TvBusEnvelope.BitstreamFormat.VFormat();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.BitstreamFormat.VFormat.Element }
     * 
     */
    public TvBusEnvelope.BitstreamFormat.VFormat.Element createTvBusEnvelopeBitstreamFormatVFormatElement() {
        return new TvBusEnvelope.BitstreamFormat.VFormat.Element();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.Showing }
     * 
     */
    public TvBusEnvelope.Showing createTvBusEnvelopeShowing() {
        return new TvBusEnvelope.Showing();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.Showing.Program }
     * 
     */
    public TvBusEnvelope.Showing.Program createTvBusEnvelopeShowingProgram() {
        return new TvBusEnvelope.Showing.Program();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.Showing.Program.Series }
     * 
     */
    public TvBusEnvelope.Showing.Program.Series createTvBusEnvelopeShowingProgramSeries() {
        return new TvBusEnvelope.Showing.Program.Series();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing }
     * 
     */
    public TvBusEnvelope.VActualShowing createTvBusEnvelopeVActualShowing() {
        return new TvBusEnvelope.VActualShowing();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element createTvBusEnvelopeVActualShowingElement() {
        return new TvBusEnvelope.VActualShowing.Element();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element.Program }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element.Program createTvBusEnvelopeVActualShowingElementProgram() {
        return new TvBusEnvelope.VActualShowing.Element.Program();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element.Program.Series }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element.Program.Series createTvBusEnvelopeVActualShowingElementProgramSeries() {
        return new TvBusEnvelope.VActualShowing.Element.Program.Series();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.RecordingQuality }
     * 
     */
    public TvBusEnvelope.RecordingQuality createTvBusEnvelopeRecordingQuality() {
        return new TvBusEnvelope.RecordingQuality();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.BitstreamFormat.VFormat.Element.VByte }
     * 
     */
    public TvBusEnvelope.BitstreamFormat.VFormat.Element.VByte createTvBusEnvelopeBitstreamFormatVFormatElementVByte() {
        return new TvBusEnvelope.BitstreamFormat.VFormat.Element.VByte();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.Showing.ShowingBits }
     * 
     */
    public TvBusEnvelope.Showing.ShowingBits createTvBusEnvelopeShowingShowingBits() {
        return new TvBusEnvelope.Showing.ShowingBits();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.Showing.Program.ShowingBits }
     * 
     */
    public TvBusEnvelope.Showing.Program.ShowingBits createTvBusEnvelopeShowingProgramShowingBits() {
        return new TvBusEnvelope.Showing.Program.ShowingBits();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.Showing.Program.ColorCode }
     * 
     */
    public TvBusEnvelope.Showing.Program.ColorCode createTvBusEnvelopeShowingProgramColorCode() {
        return new TvBusEnvelope.Showing.Program.ColorCode();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.Showing.Program.VProgramGenre }
     * 
     */
    public TvBusEnvelope.Showing.Program.VProgramGenre createTvBusEnvelopeShowingProgramVProgramGenre() {
        return new TvBusEnvelope.Showing.Program.VProgramGenre();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.Showing.Program.ShowType }
     * 
     */
    public TvBusEnvelope.Showing.Program.ShowType createTvBusEnvelopeShowingProgramShowType() {
        return new TvBusEnvelope.Showing.Program.ShowType();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.Showing.Program.Series.VSeriesGenre }
     * 
     */
    public TvBusEnvelope.Showing.Program.Series.VSeriesGenre createTvBusEnvelopeShowingProgramSeriesVSeriesGenre() {
        return new TvBusEnvelope.Showing.Program.Series.VSeriesGenre();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element.ShowingBits }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element.ShowingBits createTvBusEnvelopeVActualShowingElementShowingBits() {
        return new TvBusEnvelope.VActualShowing.Element.ShowingBits();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element.Program.VActor }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element.Program.VActor createTvBusEnvelopeVActualShowingElementProgramVActor() {
        return new TvBusEnvelope.VActualShowing.Element.Program.VActor();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element.Program.ShowingBits }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element.Program.ShowingBits createTvBusEnvelopeVActualShowingElementProgramShowingBits() {
        return new TvBusEnvelope.VActualShowing.Element.Program.ShowingBits();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element.Program.ColorCode }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element.Program.ColorCode createTvBusEnvelopeVActualShowingElementProgramColorCode() {
        return new TvBusEnvelope.VActualShowing.Element.Program.ColorCode();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element.Program.VProgramGenre }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element.Program.VProgramGenre createTvBusEnvelopeVActualShowingElementProgramVProgramGenre() {
        return new TvBusEnvelope.VActualShowing.Element.Program.VProgramGenre();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element.Program.VHost }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element.Program.VHost createTvBusEnvelopeVActualShowingElementProgramVHost() {
        return new TvBusEnvelope.VActualShowing.Element.Program.VHost();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element.Program.ShowType }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element.Program.ShowType createTvBusEnvelopeVActualShowingElementProgramShowType() {
        return new TvBusEnvelope.VActualShowing.Element.Program.ShowType();
    }

    /**
     * Create an instance of {@link TvBusEnvelope.VActualShowing.Element.Program.Series.VSeriesGenre }
     * 
     */
    public TvBusEnvelope.VActualShowing.Element.Program.Series.VSeriesGenre createTvBusEnvelopeVActualShowingElementProgramSeriesVSeriesGenre() {
        return new TvBusEnvelope.VActualShowing.Element.Program.Series.VSeriesGenre();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "element", scope = TvBusEnvelope.VActualShowing.Element.Program.VActor.class)
    public JAXBElement<String> createTvBusEnvelopeVActualShowingElementProgramVActorElement(String value) {
        return new JAXBElement<String>(_TvBusEnvelopeVActualShowingElementProgramVActorElement_QNAME, String.class, TvBusEnvelope.VActualShowing.Element.Program.VActor.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "element", scope = TvBusEnvelope.VActualShowing.Element.Program.VHost.class)
    public JAXBElement<String> createTvBusEnvelopeVActualShowingElementProgramVHostElement(String value) {
        return new JAXBElement<String>(_TvBusEnvelopeVActualShowingElementProgramVActorElement_QNAME, String.class, TvBusEnvelope.VActualShowing.Element.Program.VHost.class, value);
    }

}
