//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 11:34:19 AM PDT 
//


package com.wagstaffnet.tivo.masterlist;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.wagstaffnet.tivo.masterlist package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wagstaffnet.tivo.masterlist
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TiVoContainer }
     * 
     */
    public TiVoContainer createTiVoContainer() {
        return new TiVoContainer();
    }

    /**
     * Create an instance of {@link TiVoContainer.Item }
     * 
     */
    public TiVoContainer.Item createTiVoContainerItem() {
        return new TiVoContainer.Item();
    }

    /**
     * Create an instance of {@link TiVoContainer.Item.Links }
     * 
     */
    public TiVoContainer.Item.Links createTiVoContainerItemLinks() {
        return new TiVoContainer.Item.Links();
    }

    /**
     * Create an instance of {@link TiVoContainer.Details }
     * 
     */
    public TiVoContainer.Details createTiVoContainerDetails() {
        return new TiVoContainer.Details();
    }

    /**
     * Create an instance of {@link TiVoContainer.Item.Details }
     * 
     */
    public TiVoContainer.Item.Details createTiVoContainerItemDetails() {
        return new TiVoContainer.Item.Details();
    }

    /**
     * Create an instance of {@link TiVoContainer.Item.Links.Content }
     * 
     */
    public TiVoContainer.Item.Links.Content createTiVoContainerItemLinksContent() {
        return new TiVoContainer.Item.Links.Content();
    }

    /**
     * Create an instance of {@link TiVoContainer.Item.Links.CustomIcon }
     * 
     */
    public TiVoContainer.Item.Links.CustomIcon createTiVoContainerItemLinksCustomIcon() {
        return new TiVoContainer.Item.Links.CustomIcon();
    }

    /**
     * Create an instance of {@link TiVoContainer.Item.Links.TiVoVideoDetails }
     * 
     */
    public TiVoContainer.Item.Links.TiVoVideoDetails createTiVoContainerItemLinksTiVoVideoDetails() {
        return new TiVoContainer.Item.Links.TiVoVideoDetails();
    }

}
