//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 11:34:19 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.tivo.com/developer/calypso-protocol-1.6/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.wagstaffnet.tivo.masterlist;
