//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.08.27 at 11:34:19 AM PDT 
//


package com.wagstaffnet.tivo.masterlist;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.hibernate.type.TextType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Details">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="SourceFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="LastChangeDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TotalItems" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="UniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SortOrder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GlobalSort" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ItemStart" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="ItemCount" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="Item" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Details">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SourceFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="CopyProtected" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SourceSize" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="CaptureDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ShowingDuration" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="StartPadding" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="EndPadding" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="ShowingStartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EpisodeTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="SourceChannel" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *                             &lt;element name="SourceStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="InProgress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="HighDefinition" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ProgramId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="SeriesId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EpisodeNumber" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
 *                             &lt;element name="RecordingQuality" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *                             &lt;element name="StreamingPermission" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="TvRating" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *                             &lt;element name="ShowingBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="SourceType" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *                             &lt;element name="IdGuideSource" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Links">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Content">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                       &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Available" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="CustomIcon" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AcceptsParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="TiVoVideoDetails">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="AcceptsParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "details",
    "sortOrder",
    "globalSort",
    "itemStart",
    "itemCount",
    "item"
})
@XmlRootElement(name = "TiVoContainer")
public class TiVoContainer {
	
    @XmlElement(name = "Details", required = true)
    @OneToOne
    protected TiVoContainer.Details details;
    @XmlElement(name = "SortOrder", required = true)
    protected String sortOrder;
    @XmlElement(name = "GlobalSort", required = true)
    protected String globalSort;
    @XmlElement(name = "ItemStart")
    protected byte itemStart;
    @XmlElement(name = "ItemCount")
    protected byte itemCount;
    @XmlElement(name = "Item")
    @OneToMany
    protected List<TiVoContainer.Item> item;

    /**
     * Gets the value of the details property.
     * 
     * @return
     *     possible object is
     *     {@link TiVoContainer.Details }
     *     
     */
    public TiVoContainer.Details getDetails() {
        return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *     allowed object is
     *     {@link TiVoContainer.Details }
     *     
     */
    public void setDetails(TiVoContainer.Details value) {
        this.details = value;
    }

    /**
     * Gets the value of the sortOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSortOrder() {
        return sortOrder;
    }

    /**
     * Sets the value of the sortOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSortOrder(String value) {
        this.sortOrder = value;
    }

    /**
     * Gets the value of the globalSort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGlobalSort() {
        return globalSort;
    }

    /**
     * Sets the value of the globalSort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGlobalSort(String value) {
        this.globalSort = value;
    }

    /**
     * Gets the value of the itemStart property.
     * 
     */
    public byte getItemStart() {
        return itemStart;
    }

    /**
     * Sets the value of the itemStart property.
     * 
     */
    public void setItemStart(byte value) {
        this.itemStart = value;
    }

    /**
     * Gets the value of the itemCount property.
     * 
     */
    public byte getItemCount() {
        return itemCount;
    }

    /**
     * Sets the value of the itemCount property.
     * 
     */
    public void setItemCount(byte value) {
        this.itemCount = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the item property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TiVoContainer.Item }
     * 
     * 
     */
    public List<TiVoContainer.Item> getItem() {
        if (item == null) {
            item = new ArrayList<TiVoContainer.Item>();
        }
        return this.item;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="SourceFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="LastChangeDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TotalItems" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="UniqueId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
    		"id",
        "contentType",
        "sourceFormat",
        "title",
        "lastChangeDate",
        "totalItems",
        "uniqueId"
    })
    public static class Details {
    	@Id @GeneratedValue
        @XmlElement(name = "id", required = false)
    	Long id;
    	
        @XmlElement(name = "ContentType", required = true)
        protected String contentType;
        @XmlElement(name = "SourceFormat", required = true)
        protected String sourceFormat;
        @XmlElement(name = "Title", required = true)
        protected String title;
        @XmlElement(name = "LastChangeDate", required = true)
        protected String lastChangeDate;
        @XmlElement(name = "TotalItems")
        protected int totalItems;
        @XmlElement(name = "UniqueId", required = true)
        protected String uniqueId;

        /**
         * Gets the value of the contentType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContentType() {
            return contentType;
        }

        /**
         * Sets the value of the contentType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContentType(String value) {
            this.contentType = value;
        }

        /**
         * Gets the value of the sourceFormat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSourceFormat() {
            return sourceFormat;
        }

        /**
         * Sets the value of the sourceFormat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSourceFormat(String value) {
            this.sourceFormat = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the lastChangeDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastChangeDate() {
            return lastChangeDate;
        }

        /**
         * Sets the value of the lastChangeDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastChangeDate(String value) {
            this.lastChangeDate = value;
        }

        /**
         * Gets the value of the totalItems property.
         * 
         */
        public int getTotalItems() {
            return totalItems;
        }

        /**
         * Sets the value of the totalItems property.
         * 
         */
        public void setTotalItems(int value) {
            this.totalItems = value;
        }

        /**
         * Gets the value of the uniqueId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUniqueId() {
            return uniqueId;
        }

        /**
         * Sets the value of the uniqueId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUniqueId(String value) {
            this.uniqueId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Details">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SourceFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="CopyProtected" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SourceSize" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="CaptureDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ShowingDuration" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="StartPadding" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="EndPadding" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="ShowingStartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EpisodeTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="SourceChannel" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
     *                   &lt;element name="SourceStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="InProgress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="HighDefinition" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ProgramId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="SeriesId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EpisodeNumber" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
     *                   &lt;element name="RecordingQuality" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
     *                   &lt;element name="StreamingPermission" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="TvRating" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
     *                   &lt;element name="ShowingBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="SourceType" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
     *                   &lt;element name="IdGuideSource" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Links">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Content">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                             &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Available" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="CustomIcon" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="AcceptsParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="TiVoVideoDetails">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="AcceptsParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "details",
        "links"
    })
    @Embeddable
    public static class Item {
        @XmlElement(name = "Details", required = true)
        @Embedded
        protected TiVoContainer.Item.Details details;
        @XmlElement(name = "Links", required = true)
        @Embedded
        protected TiVoContainer.Item.Links links;

        /**
         * Gets the value of the details property.
         * 
         * @return
         *     possible object is
         *     {@link TiVoContainer.Item.Details }
         *     
         */
        public TiVoContainer.Item.Details getDetails() {
            return details;
        }

        /**
         * Sets the value of the details property.
         * 
         * @param value
         *     allowed object is
         *     {@link TiVoContainer.Item.Details }
         *     
         */
        public void setDetails(TiVoContainer.Item.Details value) {
            this.details = value;
        }

        /**
         * Gets the value of the links property.
         * 
         * @return
         *     possible object is
         *     {@link TiVoContainer.Item.Links }
         *     
         */
        public TiVoContainer.Item.Links getLinks() {
            return links;
        }

        /**
         * Sets the value of the links property.
         * 
         * @param value
         *     allowed object is
         *     {@link TiVoContainer.Item.Links }
         *     
         */
        public void setLinks(TiVoContainer.Item.Links value) {
            this.links = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SourceFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="CopyProtected" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SourceSize" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="Duration" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="CaptureDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ShowingDuration" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="StartPadding" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="EndPadding" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="ShowingStartTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EpisodeTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="SourceChannel" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
         *         &lt;element name="SourceStation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="InProgress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="HighDefinition" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ProgramId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="SeriesId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EpisodeNumber" type="{http://www.w3.org/2001/XMLSchema}short" minOccurs="0"/>
         *         &lt;element name="RecordingQuality" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
         *         &lt;element name="StreamingPermission" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="TvRating" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
         *         &lt;element name="ShowingBits" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="SourceType" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
         *         &lt;element name="IdGuideSource" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contentType",
            "sourceFormat",
            "title",
            "copyProtected",
            "sourceSize",
            "duration",
            "captureDate",
            "showingDuration",
            "startPadding",
            "endPadding",
            "showingStartTime",
            "episodeTitle",
            "description",
            "sourceChannel",
            "sourceStation",
            "inProgress",
            "highDefinition",
            "programId",
            "seriesId",
            "episodeNumber",
            "recordingQuality",
            "streamingPermission",
            "tvRating",
            "showingBits",
            "sourceType",
            "idGuideSource"
        })
        @Embeddable
        public static class Details {
            @XmlElement(name = "ContentType", required = true)
            protected String contentType;
            @XmlElement(name = "SourceFormat", required = true)
            protected String sourceFormat;
            @XmlElement(name = "Title", required = true)
            protected String title;
            @XmlElement(name = "CopyProtected")
            protected String copyProtected;
            @XmlElement(name = "SourceSize")
            protected long sourceSize;
            @XmlElement(name = "Duration")
            protected int duration;
            @XmlElement(name = "CaptureDate", required = true)
            protected String captureDate;
            @XmlElement(name = "ShowingDuration")
            protected int showingDuration;
            @XmlElement(name = "StartPadding")
            protected int startPadding;
            @XmlElement(name = "EndPadding")
            protected int endPadding;
            @XmlElement(name = "ShowingStartTime", required = true)
            protected String showingStartTime;
            @XmlElement(name = "EpisodeTitle")
            protected String episodeTitle;
            @XmlElement(name = "Description")
            @Column(columnDefinition="text")
            protected String description;
            @XmlElement(name = "SourceChannel")
            protected int sourceChannel;
            @XmlElement(name = "SourceStation")
            protected String sourceStation;
            @XmlElement(name = "InProgress")
            protected String inProgress;
            @XmlElement(name = "HighDefinition", required = true)
            protected String highDefinition;
            @XmlElement(name = "ProgramId", required = true)
            protected String programId;
            @XmlElement(name = "SeriesId", required = true)
            protected String seriesId;
            @XmlElement(name = "EpisodeNumber")
            protected int episodeNumber;
            @XmlElement(name = "RecordingQuality")
            protected Byte recordingQuality;
            @XmlElement(name = "StreamingPermission", required = true)
            protected String streamingPermission;
            @XmlElement(name = "TvRating")
            protected Byte tvRating;
            @XmlElement(name = "ShowingBits")
            protected int showingBits;
            @XmlElement(name = "SourceType")
            protected Byte sourceType;
            @XmlElement(name = "IdGuideSource")
            protected Integer idGuideSource;

            /**
             * Gets the value of the contentType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContentType() {
                return contentType;
            }

            /**
             * Sets the value of the contentType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContentType(String value) {
                this.contentType = value;
            }

            /**
             * Gets the value of the sourceFormat property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceFormat() {
                return sourceFormat;
            }

            /**
             * Sets the value of the sourceFormat property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceFormat(String value) {
                this.sourceFormat = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the copyProtected property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCopyProtected() {
                return copyProtected;
            }

            /**
             * Sets the value of the copyProtected property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCopyProtected(String value) {
                this.copyProtected = value;
            }

            /**
             * Gets the value of the sourceSize property.
             * 
             */
            public long getSourceSize() {
                return sourceSize;
            }

            /**
             * Sets the value of the sourceSize property.
             * 
             */
            public void setSourceSize(long value) {
                this.sourceSize = value;
            }

            /**
             * Gets the value of the duration property.
             * 
             */
            public int getDuration() {
                return duration;
            }

            /**
             * Sets the value of the duration property.
             * 
             */
            public void setDuration(int value) {
                this.duration = value;
            }

            /**
             * Gets the value of the captureDate property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCaptureDate() {
                return captureDate;
            }

            /**
             * Sets the value of the captureDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCaptureDate(String value) {
                this.captureDate = value;
            }

            /**
             * Gets the value of the showingDuration property.
             * 
             */
            public int getShowingDuration() {
                return showingDuration;
            }

            /**
             * Sets the value of the showingDuration property.
             * 
             */
            public void setShowingDuration(int value) {
                this.showingDuration = value;
            }

            /**
             * Gets the value of the startPadding property.
             * 
             */
            public int getStartPadding() {
                return startPadding;
            }

            /**
             * Sets the value of the startPadding property.
             * 
             */
            public void setStartPadding(int value) {
                this.startPadding = value;
            }

            /**
             * Gets the value of the endPadding property.
             * 
             */
            public int getEndPadding() {
                return endPadding;
            }

            /**
             * Sets the value of the endPadding property.
             * 
             */
            public void setEndPadding(int value) {
                this.endPadding = value;
            }

            /**
             * Gets the value of the showingStartTime property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getShowingStartTime() {
                return showingStartTime;
            }

            /**
             * Sets the value of the showingStartTime property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setShowingStartTime(String value) {
                this.showingStartTime = value;
            }

            /**
             * Gets the value of the episodeTitle property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEpisodeTitle() {
                return episodeTitle;
            }

            /**
             * Sets the value of the episodeTitle property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEpisodeTitle(String value) {
                this.episodeTitle = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the sourceChannel property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public int getSourceChannel() {
                return sourceChannel;
            }

            /**
             * Sets the value of the sourceChannel property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setSourceChannel(int value) {
                this.sourceChannel = value;
            }

            /**
             * Gets the value of the sourceStation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSourceStation() {
                return sourceStation;
            }

            /**
             * Sets the value of the sourceStation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSourceStation(String value) {
                this.sourceStation = value;
            }

            /**
             * Gets the value of the inProgress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInProgress() {
                return inProgress;
            }

            /**
             * Sets the value of the inProgress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInProgress(String value) {
                this.inProgress = value;
            }

            /**
             * Gets the value of the highDefinition property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHighDefinition() {
                return highDefinition;
            }

            /**
             * Sets the value of the highDefinition property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHighDefinition(String value) {
                this.highDefinition = value;
            }

            /**
             * Gets the value of the programId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProgramId() {
                return programId;
            }

            /**
             * Sets the value of the programId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProgramId(String value) {
                this.programId = value;
            }

            /**
             * Gets the value of the seriesId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSeriesId() {
                return seriesId;
            }

            /**
             * Sets the value of the seriesId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSeriesId(String value) {
                this.seriesId = value;
            }

            /**
             * Gets the value of the episodeNumber property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public int getEpisodeNumber() {
                return episodeNumber;
            }

            /**
             * Sets the value of the episodeNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setEpisodeNumber(int value) {
                this.episodeNumber = value;
            }

            /**
             * Gets the value of the recordingQuality property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getRecordingQuality() {
                return recordingQuality;
            }

            /**
             * Sets the value of the recordingQuality property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setRecordingQuality(Byte value) {
                this.recordingQuality = value;
            }

            /**
             * Gets the value of the streamingPermission property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStreamingPermission() {
                return streamingPermission;
            }

            /**
             * Sets the value of the streamingPermission property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStreamingPermission(String value) {
                this.streamingPermission = value;
            }

            /**
             * Gets the value of the tvRating property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getTvRating() {
                return tvRating;
            }

            /**
             * Sets the value of the tvRating property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setTvRating(Byte value) {
                this.tvRating = value;
            }

            /**
             * Gets the value of the showingBits property.
             * 
             */
            public int getShowingBits() {
                return showingBits;
            }

            /**
             * Sets the value of the showingBits property.
             * 
             */
            public void setShowingBits(int value) {
                this.showingBits = value;
            }

            /**
             * Gets the value of the sourceType property.
             * 
             * @return
             *     possible object is
             *     {@link Byte }
             *     
             */
            public Byte getSourceType() {
                return sourceType;
            }

            /**
             * Sets the value of the sourceType property.
             * 
             * @param value
             *     allowed object is
             *     {@link Byte }
             *     
             */
            public void setSourceType(Byte value) {
                this.sourceType = value;
            }

            /**
             * Gets the value of the idGuideSource property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getIdGuideSource() {
                return idGuideSource;
            }

            /**
             * Sets the value of the idGuideSource property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setIdGuideSource(Integer value) {
                this.idGuideSource = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Content">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                   &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Available" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="CustomIcon" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="AcceptsParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="TiVoVideoDetails">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="AcceptsParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content",
            "customIcon",
            "tiVoVideoDetails"
        })
        @Embeddable
        public static class Links {
            @XmlElement(name = "Content", required = true)
            @Embedded
            protected TiVoContainer.Item.Links.Content content;
            @XmlElement(name = "CustomIcon")
            @Embedded
            protected TiVoContainer.Item.Links.CustomIcon customIcon;
            @XmlElement(name = "TiVoVideoDetails", required = true)
            @Embedded
            protected TiVoContainer.Item.Links.TiVoVideoDetails tiVoVideoDetails;

            /**
             * Gets the value of the content property.
             * 
             * @return
             *     possible object is
             *     {@link TiVoContainer.Item.Links.Content }
             *     
             */
            public TiVoContainer.Item.Links.Content getContent() {
                return content;
            }

            /**
             * Sets the value of the content property.
             * 
             * @param value
             *     allowed object is
             *     {@link TiVoContainer.Item.Links.Content }
             *     
             */
            public void setContent(TiVoContainer.Item.Links.Content value) {
                this.content = value;
            }

            /**
             * Gets the value of the customIcon property.
             * 
             * @return
             *     possible object is
             *     {@link TiVoContainer.Item.Links.CustomIcon }
             *     
             */
            public TiVoContainer.Item.Links.CustomIcon getCustomIcon() {
                return customIcon;
            }

            /**
             * Sets the value of the customIcon property.
             * 
             * @param value
             *     allowed object is
             *     {@link TiVoContainer.Item.Links.CustomIcon }
             *     
             */
            public void setCustomIcon(TiVoContainer.Item.Links.CustomIcon value) {
                this.customIcon = value;
            }

            /**
             * Gets the value of the tiVoVideoDetails property.
             * 
             * @return
             *     possible object is
             *     {@link TiVoContainer.Item.Links.TiVoVideoDetails }
             *     
             */
            public TiVoContainer.Item.Links.TiVoVideoDetails getTiVoVideoDetails() {
                return tiVoVideoDetails;
            }

            /**
             * Sets the value of the tiVoVideoDetails property.
             * 
             * @param value
             *     allowed object is
             *     {@link TiVoContainer.Item.Links.TiVoVideoDetails }
             *     
             */
            public void setTiVoVideoDetails(TiVoContainer.Item.Links.TiVoVideoDetails value) {
                this.tiVoVideoDetails = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *         &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Available" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "url",
                "contentType",
                "available"
            })
            @Embeddable
            public static class Content {
                @XmlElement(name = "Url", required = true)
                @XmlSchemaType(name = "anyURI")
                protected String url;
                @XmlElement(name = "ContentType", required = true)
                protected String contentType;
                @XmlElement(name = "Available")
                protected String available;

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the contentType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContentType() {
                    return contentType;
                }

                /**
                 * Sets the value of the contentType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContentType(String value) {
                    this.contentType = value;
                }

                /**
                 * Gets the value of the available property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAvailable() {
                    return available;
                }

                /**
                 * Sets the value of the available property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAvailable(String value) {
                    this.available = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="AcceptsParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "url",
                "contentType",
                "acceptsParams"
            })
            @Embeddable
            public static class CustomIcon {
                @XmlElement(name = "Url", required = true)
                protected String url;
                @XmlElement(name = "ContentType", required = true)
                protected String contentType;
                @XmlElement(name = "AcceptsParams", required = true)
                protected String acceptsParams;

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the contentType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContentType() {
                    return contentType;
                }

                /**
                 * Sets the value of the contentType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContentType(String value) {
                    this.contentType = value;
                }

                /**
                 * Gets the value of the acceptsParams property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAcceptsParams() {
                    return acceptsParams;
                }

                /**
                 * Sets the value of the acceptsParams property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAcceptsParams(String value) {
                    this.acceptsParams = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="ContentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="AcceptsParams" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "url",
                "contentType",
                "acceptsParams"
            })
            @Embeddable
            public static class TiVoVideoDetails {
                @XmlElement(name = "Url", required = true)
                protected String url;
                @XmlElement(name = "ContentType", required = true)
                protected String contentType;
                @XmlElement(name = "AcceptsParams", required = true)
                protected String acceptsParams;

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the contentType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getContentType() {
                    return contentType;
                }

                /**
                 * Sets the value of the contentType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setContentType(String value) {
                    this.contentType = value;
                }

                /**
                 * Gets the value of the acceptsParams property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAcceptsParams() {
                    return acceptsParams;
                }

                /**
                 * Sets the value of the acceptsParams property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAcceptsParams(String value) {
                    this.acceptsParams = value;
                }

            }

        }
    }

}
